title: Kitsune Mods Resource
description: 3DS & Wii U System UI Customisations Resource
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: dark
  nav_pages:
    - about.md
  show_excerpts: false
